import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import ThemeProvider from "@/providers/theme_provider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body>
				<ThemeProvider
					enableSystem
					attribute='class'
					defaultTheme='light '>
					<Navbar />
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
